# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-10 05:06
from __future__ import unicode_literals

import diabetes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]


