# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-10 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0001_initial'),
    ]


