# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-10 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0002_auto_20180309_2147'),
    ]

    operations = [

    ]
