# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-11 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0003_doctors'),
    ]


