# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-11 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0004_auto_20180310_2309'),
    ]


