# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-13 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0005_auto_20180311_0040'),
    ]


