# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-13 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0006_auto_20180312_2321'),
    ]

