# Generated by Django 2.0.3 on 2018-03-16 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0007_auto_20180312_2330'),
    ]


