# Generated by Django 2.0.3 on 2018-03-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0008_remove_city_description'),
    ]

