# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-25 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diabetes', '0009_auto_20180319_1501'),
    ]



