# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-25 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diabetes', '0011_auto_20180325_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=50)),
                ('date_created', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('longtitude', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diabetes.City')),
            ],
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnant', models.CharField(max_length=50)),
                ('glucose', models.CharField(max_length=50)),
                ('pressure', models.IntegerField(blank=True, null=True)),
                ('skin', models.IntegerField(blank=True, null=True)),
                ('insulin', models.IntegerField(blank=True, null=True)),
                ('mass', models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True)),
                ('predegree', models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True)),
                ('age', models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True)),
                ('variable', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctors',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diabetes.Facility'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diabetes.Disease'),
        ),
    ]
