# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-25 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0012_auto_20180325_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='age',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='mass',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='predegree',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
