# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-25 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0013_auto_20180325_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='speciality',
        ),
    ]
