# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-30 21:56
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0014_remove_doctors_speciality'),
    ]

    operations = [


    ]
