# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-06 21:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diabetes', '0015_auto_20180330_1456'),
    ]

    operations = [


    ]
