# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-30 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0015_auto_20180330_1456'),
    ]

