# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-14 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0016_auto_20180406_1407'),
    ]



